[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "simex"
version = "0.1.0"
description = "SIMEX Python bindings"
authors = [{ name = "SIMEX", email = "devnull@example.com" }]
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
simex = ["*.pyi", "_core*.so"]
